# TODO ENDPOINTS 
# endpoint to get a particular todo 
###
GET http://127.0.0.1:8000/api/todos/12


# endpoint to delete a particular todo 
###
DELETE  http://127.0.0.1:8000/api/todos/12/delete/


# endpoint to update a particular todo 
###
PUT http://127.0.0.1:8000/api/todos/2/update/
Content-Type: application/json

{
    "name" : "grocery and market",
    "target_time" : "03:30"
}

# endpoint to create a todo task 
###
POST http://127.0.0.1:8000/api/todos/create/
Content-Type:  application/json

{
    "name" : "school"
}


# endpoint to get all todos 
###
GET http://127.0.0.1:8000/api/todos/


# endpoint to get all todos or create todo 
###
POST http://127.0.0.1:8000/api/todos/create_or_get/
Content-Type: application/json

{
    "name" : "market or library"
}

