# Generated by Django 4.1.5 on 2023-01-23 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_time', models.TimeField(null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('start_at', models.TimeField(blank=True, null=True)),
                ('completed_at', models.TimeField(blank=True, null=True)),
                ('is_suspended', models.BooleanField(blank=True, default=False, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
